# Generated by Django 5.1 on 2024-08-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("image_url", models.URLField(blank=True, max_length=255, null=True)),
                ("link", models.URLField(blank=True, max_length=255, null=True)),
                ("benefits", models.JSONField(default=list)),
                ("categories", models.JSONField(default=list)),
            ],
        ),
    ]
