# Generated by Django 5.1 on 2024-08-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("card_recommendation", "0002_alter_card_image_url_alter_card_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="card",
            old_name="categories",
            new_name="details",
        ),
        migrations.AlterField(
            model_name="card",
            name="image_url",
            field=models.URLField(default=""),
        ),
    ]
